var product = [{
    "id": 0,
    "title": "",
    "price": "",
    "restaurant": "",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/1665px-No-Image-Placeholder.svg.png",
    "energiekj": "",
    "energiekcal": "",
    "koolhydraten": "",
    "suikers": "",
    "vezels": "",
    "vet": "",
    "verzadigdvet": "",
    "eiwit": ""
}, {
    "id": 1,
    "title": "Big Mac",
    "price": "5.10",
    "restaurant": "Mc Donalds",
    "image": "Afbeeldingen/Hamburgers/McDonalds/BigMac.png",
    "energiekj": 2191,
    "energiekcal": 524,
    "koolhydraten": 43,
    "suikers": 8.9,
    "vezels": 3.4,
    "vet": 27,
    "verzadigdvet": 9.9,
    "eiwit": 27,
}, {
  "id": 2,
  "title": "Mc Chicken",
  "price": "5.10",
  "restaurant": "Mc Donalds",
  "image": "Afbeeldingen/Hamburgers/McDonalds/McChicken.png",
  "energiekj": 1960,
  "energiekcal": 468,
  "koolhydraten": 48,
  "suikers": 7.3,
  "vezels": 3.4,
  "vet": 21,
  "verzadigdvet": 2.5,
  "eiwit": 21,
}, {
  "id": 3,
  "title": "Whopper",
  "price": "7.10",
  "restaurant": "Burger King",
  "image": "Afbeeldingen/Hamburgers/BurgerKing/Whopper.png",
  "energiekj": 2666,
  "energiekcal": 637.2,
  "koolhydraten": 49.3,
  "suikers": 12.6,
  "vezels": 3.5,
  "vet": 34.7,
  "verzadigdvet": 9.6,
  "eiwit": 30,
}, {
  "id": 4,
  "title": "Classic Master",
  "price": "11,45",
  "restaurant": "Burger King",
  "image": "Afbeeldingen/Hamburgers/BurgerKing/ClassicMaster.png",
  "energiekj": 3740,
  "energiekcal": 893.9,
  "koolhydraten": 58.2,
  "suikers": 15.8,
  "vezels": 5.8,
  "vet": 52.4,
  "verzadigdvet": 20.1,
  "eiwit": 44.1,
}, {
  "id": 5,
  "title": "Original Burger",
  "price": "7,95",
  "restaurant": "KFC",
  "image": "Afbeeldingen/Hamburgers/KFC/OriginalBurger.png",
  "energiekj": 1892.8,
  "energiekcal": 452.4,
  "koolhydraten": 41.5,
  "suikers": 5.1,
  "vezels": 3.3,
  "vet": 19.6,
  "verzadigdvet": 2.4,
  "eiwit": 25.8,
}, {
  "id": 6,
  "title": "Zinger Burger",
  "price": "7,95",
  "restaurant": "KFC",
  "image": "Afbeeldingen/Hamburgers/KFC/ZingerBurger.png",
  "energiekj": 2154.3,
  "energiekcal": 514.8,
  "koolhydraten": 43.6,
  "suikers": 5.1,
  "vezels": 3.4,
  "vet": 25.5,
  "verzadigdvet": 3.4,
  "eiwit": 26.0,
}]